"""create weekly_reports table

Revision ID: d9b8574985e0
Revises: 8585a2627c2f
Create Date: 2026-09-06 02:08:27.414462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b8574985e0'
down_revision: Union[str, Sequence[str], None] = '8585a2627c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('highlights', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='unique_user_week_start')
    )
    op.create_index(op.f('ix_weekly_reports_user_id'), 'weekly_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_week_start'), 'weekly_reports', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_reports_week_start'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_user_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    # ### end Alembic commands ###
